version: '3'


services:
  app:

    build:
    # dondequiero que busque el archivo del dockerfile ejemplo una carpeta docker o algo así
      context: .
      target: prod      #para produccion
      dockerfile: Dockerfile
    # command: yarn start:dev           en vez de en el dockerfile tambien se puede acá
    image: juank27/teslo-shop-backend:2.0.0   # o latest    #para que me de un tag en la image ls sino seria <none>
    container_name: nest-app
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}
  
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data


volumes:
  postgres-db:
    external: false